### ISSUE TITLE
Link shows button even if showLinkButton is false

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-ui#326] opened 2023-04-13 14:19 UTC
This bug may not exist anymore if player is not up to date.

**Comment by spaenleh** [comment] 2023-04-14 07:01
This bug is caused by the implementation of the default value in player. See https://github.com/graasp/graasp-player/blob/5c01bec7157f12f879e45a782077794c836765cb/src/modules/item/Item.tsx#L282 where the value of the `showLinkButton` is combined with the coalescing opperator `||` we should use the `??` instead so `false` would be kept. Currently `false` is replaced by the default `true`. We could also simply remove the default, as ui has `showButton` prop default to `true` when it is `undefined`.

**Comment by spaenleh** [comment] 2023-04-14 12:38
Fixed in https://github.com/graasp/graasp-player/pull/229

**Closed by spaenleh** 2023-04-14 12:38 UTC
Labels: bug
